# Generated by Django 5.1.1 on 2024-09-16 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientId", models.PositiveIntegerField(null=True)),
                ("doctorId", models.PositiveIntegerField(null=True)),
                ("patientName", models.CharField(max_length=40, null=True)),
                ("doctorName", models.CharField(max_length=40, null=True)),
                ("appointmentDate", models.DateField(auto_now=True)),
                ("description", models.TextField(max_length=500)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PatientDischargeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientId", models.PositiveIntegerField(null=True)),
                ("patientName", models.CharField(max_length=40)),
                ("assignedDoctorName", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20, null=True)),
                ("treatment", models.CharField(max_length=100, null=True)),
                ("admitDate", models.DateField()),
                ("releaseDate", models.DateField()),
                ("daySpent", models.PositiveIntegerField()),
                ("roomCharge", models.PositiveIntegerField()),
                ("medicineCost", models.PositiveIntegerField()),
                ("doctorFee", models.PositiveIntegerField()),
                ("OtherCharge", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/DoctorProfilePic/"
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20, null=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologists", "Dermatologists"),
                            (
                                "Emergency Medicine Specialists",
                                "Emergency Medicine Specialists",
                            ),
                            ("Allergists/Immunologists", "Allergists/Immunologists"),
                            ("Anesthesiologists", "Anesthesiologists"),
                            ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                        ],
                        default="Cardiologist",
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/PatientProfilePic/"
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20)),
                ("symptoms", models.CharField(max_length=100)),
                ("assignedDoctorId", models.PositiveIntegerField(null=True)),
                ("admitDate", models.DateField(auto_now=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
